# Generated by Django 3.2.22 on 2023-11-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetballer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetballer',
        ),
    ]
