# Generated by Django 3.2.22 on 2023-10-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20231024_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Omschrijving',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Datum',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Kosten',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Tijdstip_aanvang',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Tijdstip_einde',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
